[phases.setup]
cmds = ["apt-get update && apt-get install -y sqlite3"]

[phases.build]
cmds = ["composer install --no-dev"]

[phases.install]
cmds = ["cp .env.railway .env", "php artisan key:generate"]

[start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"